import {
  CalendarIcon,
  CogIcon,
  ComposeIcon,
  DocumentsIcon,
  FilterIcon,
  HomeIcon,
  TiersIcon,
  UsersIcon,
  BookIcon,
  DocumentTextIcon,
  DocumentVideoIcon,
  EarthAmericasIcon,
} from "@sanity/icons";

export const myStructure = (S) =>
  S.list()
    .title("Menu")
    .items([
      S.listItem()
        .title("Home")
        .icon(HomeIcon)
        .child(S.document().schemaType("home").title("Home")),
      S.listItem()
        .title("Pages")
        .icon(DocumentsIcon)
        .child(S.documentTypeList("page").title("Pages")),
      S.listItem()
        .title("Grøn Blok Magazine")
        .icon(BookIcon)
        .child(
          S.list()
            .title("Menus")
            .items([
              S.listItem()
                .title("Articles")
                .icon(DocumentTextIcon)
                .child(S.documentTypeList("article").title("Articles")),
              S.listItem()
                .title("Videos")
                .icon(DocumentVideoIcon)
                .child(S.documentTypeList("video").title("Videos")),
              S.listItem()
                .title("Podcast")
                .icon(DocumentVideoIcon)
                .child(S.documentTypeList("podcast").title("Podcast")),
              S.listItem()
                .title("Advice")
                .icon(DocumentTextIcon)
                .child(S.documentTypeList("advice").title("Advice")),
              S.listItem()
                .title("Reports")
                .icon(DocumentTextIcon)
                .child(S.documentTypeList("report").title("Reports")),
            ])
        ),
      S.divider(),
      S.listItem()
        .title("Events")
        .icon(CalendarIcon)
        .child(
          S.documentTypeList("event")
            .title("Events")
            .defaultOrdering([{ field: "date", direction: "asc" }])
        ),
      S.listItem()
        .title("Projects")
        .icon(EarthAmericasIcon)
        .child(
          S.documentTypeList("project")
            .title("Projects")
            .defaultOrdering([{ field: "date", direction: "asc" }])
        ),
      S.divider(),
      S.listItem()
        .title("Templates")
        .icon(TiersIcon)
        .child(S.documentTypeList("template").title("Templates")),
      S.listItem()
        .title("Settings")
        .icon(CogIcon)
        .child(S.document().schemaType("settings").title("Settings")),
    ]);
