/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    borderRadius: {
      none: "0",
      sm: "3px",
      DEFAULT: "6px",
      lg: "12px",
      full: "9999px",
    },
    fontSize: {
      "h1-web": "var(--font-size-web-H1)",
      "h2-web": "var(--font-size-web-H2)",
      "h3-web": "var(--font-size-web-H3)",
      "h4-web": "var(--font-size-web-H4)",
      "h5-web": "var(--font-size-web-H5)",
      "h6-web": "var(--font-size-web-H6)",
      "h7-web": "var(--font-size-web-H7)",
      "body-web": "var(--font-size-web-body)",
      "body-xl-web": "var(--font-size-web-body-xl)",
      "button-web": "var(--font-size-web-button)",
      "button-xl-web": "var(--font-size-web-button-xl)",
      h1: "var(--font-size-mobile-H1)",
      h2: "var(--font-size-mobile-H2)",
      h3: "var(--font-size-mobile-H3)",
      h4: "var(--font-size-mobile-H4)",
      h5: "var(--font-size-mobile-H5)",
      h6: "var(--font-size-mobile-H6)",
      h7: "var(--font-size-mobile-H7)",
      body: "var(--font-size-mobile-body)",
      "body-xl": "var(--font-size-mobile-body-xl)",
      button: "var(--font-size-mobile-button)",
      "button-xl": "var(--font-size-mobile-button-xl)",
    },
    fontWeight: {
      regular: "var(--font-weight-regular)",
      black: "var(--font-weight-black)",
      bold: "var(--font-weight-bold)",
    },
    letterSpacing: {
      1: "var(--letter-spacing-1)",
      2: "var(--letter-spacing-2)",
      3: "var(--letter-spacing-3)",
      4: "var(--letter-spacing-4)",
    },
    extend: {
      colors: {
        darkGreen: "#12471e",
        "darkGreen-75": "rgba(18, 71, 30, 0.75)",
        lightBeige: "#f9f4e8",
        lightGreen: "#84b85c",
        yellowAccent: "#e8ff8e",
        orangeAccent: "#ff8c00",
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic": "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      fontFamily: {
        sans: ["Taviraj", "serif"],
        chivo: ["Chivo", "sans-serif"],
      },
    },
  },
  plugins: [],
};
